%define text_aligner_version 0.08

Name:           perl-Text-Table+Aligner
Version:        1.135
Release:        1%{?dist}
Summary:        Organize Data in Tables

License:        ISC License
URL:            https://metacpan.org/dist/Text-Table
Source0:        https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Text-Table-%{version}.tar.gz
Source1:        https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Text-Aligner-%{text_aligner_version}.tar.gz

BuildArch:      noarch

BuildRequires:  perl >= 5.008
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)

# Only needed on RHEL 8+
%if 0%{?rhel} >= 8
BuildRequires:  perl-generators
%endif

Requires: perl
Requires: perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

Provides: perl(Text::Table) = %{version}
Provides: perl(Text::Aligner) = %{text_aligner_version}

%description
Organization of data in table form is a time-honored and useful method of data representation. While
columns of data are trivially generated by computer through formatted output, even simple tasks like
keeping titles aligned with the data columns are not trivial, and the one-shot solutions one comes up with
tend to be particularly hard to maintain. Text::Table allows you to create and maintain tables that adapt to
alignment requirements as you use them.

%prep
%setup -q -T -D -b 1 -n Text-Aligner-%{text_aligner_version}
%setup -q -T -D -b 0 -n Text-Table-%{version}

%build
# build Text::Aligner first
pushd %{_builddir}/Text-Aligner-%{text_aligner_version}
    %{__perl} Makefile.PL INSTALLDIRS=vendor
    make %{?_smp_mflags}
popd

PERL5LIB=%{_builddir}/Text-Aligner-%{text_aligner_version}/blib/lib:%{_builddir}/Text-Aligner-%{text_aligner_version}/blib/arch %{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf %{buildroot}

pushd %{_builddir}/Text-Aligner-%{text_aligner_version}
    make pure_install PERL_INSTALL_ROOT=%{buildroot}
popd

make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%check
pushd %{_builddir}/Text-Aligner-%{text_aligner_version}
    make test
popd

PERL5LIB=%{_builddir}/Text-Aligner-%{text_aligner_version}/blib/lib:%{_builddir}/Text-Aligner-%{text_aligner_version}/blib/arch make test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*
