Name:           perl-Text-Table
Version:        1.135
Release:        1%{?dist}
Summary:        Organize Data in Tables

License:        GPL-1.0-or-later OR Artistic-1.0-Perl
URL:            https://metacpan.org/dist/Text-Table
Source0:        https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Text-Table-%{version}.tar.gz

BuildArch:      noarch

BuildRequires:  perl >= 0:5.008
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Text::Aligner)
BuildRequires:  perl(Test::More) >= 0.88

# Only needed on RHEL 8+, not present on RHEL 7
%if 0%{?rhel} >= 8
BuildRequires:  perl-generators
%endif

Requires:       perl
Requires:       perl(List::Util)
Requires:       perl(Text::Aligner)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

Provides:       perl(Text::Table) = %{version}

%description
Organization of data in table form is a time-honored and useful method of
data representation. While columns of data are trivially generated by
computer through formatted output, even simple tasks like keeping titles
aligned with the data columns are not trivial, and the one-shot solutions
one comes up with tend to be particularly hard to maintain. Text::Table
allows you to create and maintain tables that adapt to alignment
requirements as you use them.

%prep
%setup -q -n Text-Table-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes dist.ini examples LICENSE META.json README weaver.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jul 01 2025 Thien Nguyen <nthien86@gmail.com> 1.135-1
- Initial RPM release for Text::Table Perl module
